### ISSUE TITLE
Can I give genome FASTA as an input?

### ISSUE THREAD

**Issue by mshrngci118** [martaS95/PhagePromoter#1]
I was trying to predict phage promoter region for given genome FASTA file.
However, it keeps giving me back "Invalid argument error". 
I've attached error massage and UI image for how I set it to run.

Fatal error: Exit code 126 ()
/export/galaxy-central/database/job_working_directory/002/2550/tool_script.sh: line 73: /export/tool_deps/_conda/envs/mulled-v1-d7e02de4dc8cf90bc17a8fc1486d04e19f03edb0d6e7cd4de5385beda6b9903e/bin/python3: Invalid argument

![image](https://user-images.githubusercontent.com/40280869/109458602-74ed5900-7aa0-11eb-819e-e3dca6336b89.png)

**Comment by martaS95** [comment]
Yes, you can give genome FASTA to PhagePromoter. This error was fixed and now we hope you can run our tool with your data without any problem.

**Comment by mshrngci118** [comment]
@martaS95 
Thanks for fixing the bug.
I could upload my genome Fasta file, but unfortunately, I have got other errors during the data processes.
I tried to report issues via Galaxy website, but I could not send it to you.
Should I open new issues?

**Comment by martaS95** [comment]
Hi! Yes, you can open a new issue and show me the errors that you get when running phagepromoter.
